/* Thuật ngữ giao diện — tiếng Việt */
const VI = {
  pages: {
    dashboard: 'Tổng quan',
    onboarding: 'Thiết lập shop',
    'products-setup': 'Ra mắt sản phẩm',
    store: 'Tối ưu cửa hàng',
    compliance: 'Tuân thủ & chính sách',
    education: 'Đào tạo seller',
    portfolio: 'Chiến lược sản phẩm',
    channels: 'Đa kênh',
    datahub: 'Trung tâm dữ liệu',
    products: 'Vận hành sản phẩm',
    orders: 'Trung tâm đơn hàng',
    inventory: 'Quản lý tồn kho',
    returns: 'Hoàn & hủy đơn',
    affiliate: 'Trung tâm tiếp thị liên kết',
    koc: 'Quản lý KOC',
    agency: 'Quản lý agency',
    samples: 'Theo dõi gửi mẫu',
    content: 'Lịch nội dung',
    livestream: 'Vận hành livestream',
    campaigns: 'Trung tâm chiến dịch',
    vouchers: 'Quản lý voucher',
    ads: 'Quảng cáo Spark',
    executive: 'Bảng điều khiển điều hành',
    revenue: 'Phân tích doanh thu',
    profit: 'Lãi lỗ & biên lợi nhuận',
    costs: 'Phân tích chi phí',
    'product-analytics': 'Phân tích sản phẩm',
    'affiliate-analytics': 'Phân tích tiếp thị liên kết',
    'creator-analytics': 'Bảng điểm KOC',
    'content-analytics': 'Phân tích nội dung',
    'live-analytics': 'Phân tích livestream',
    'customer-analytics': 'Phân tích khách hàng',
    team: 'Quản lý nhóm',
    'growth-assistant': 'Trợ lý tăng trưởng AI',
    alerts: 'Cảnh báo thông minh',
    opportunities: 'Cơ hội tăng trưởng',
    forecast: 'Dự báo',
    benchmark: 'So sánh thị trường',
    actions: 'Trung tâm quyết định',
    automation: 'Tự động hóa',
    workflows: 'Trung tâm quy trình',
    optimization: 'Tối ưu tăng trưởng',
    notifications: 'Trung tâm thông báo',
    audit: 'Kiểm toán & quản trị',
    settings: 'Cài đặt & phân quyền'
  },
  status: {
    active: 'Đang hoạt động', pending: 'Chờ xử lý', processing: 'Đang xử lý',
    shipped: 'Đang giao', delivered: 'Hoàn thành', cancelled: 'Đã hủy',
    return_requested: 'Yêu cầu hoàn', paused: 'Tạm dừng', scheduled: 'Đã lên lịch',
    draft: 'Bản nháp', published: 'Đã đăng', converted: 'Chuyển đổi',
    no_content: 'Chưa có nội dung', review: 'Đang duyệt', low_stock: 'Tồn kho thấp',
    connected: 'Đã kết nối', synced: 'Đã đồng bộ', live: 'Trực tiếp', partial: 'Một phần',
    approved: 'Đã duyệt', in_progress: 'Đang thực hiện', refunded: 'Đã hoàn tiền',
    pending_review: 'Chờ duyệt', ok: 'Ổn định', new: 'Mới', compliant: 'Tuân thủ',
    monitoring: 'Theo dõi', action_required: 'Cần xử lý', warning: 'Cảnh báo',
    critical: 'Khẩn cấp', info: 'Thông tin', high: 'Cao', medium: 'Trung bình',
    revenue: 'Tạo doanh thu', affiliate: 'Tiếp thị liên kết', livestream: 'Livestream',
    ads: 'Quảng cáo', organic: 'Tự nhiên', video: 'Video', spark: 'Spark',
    product: 'Sản phẩm', promotion: 'Khuyến mãi'
  },
  labels: {
    Setup: 'Thiết lập', 'Shop Health': 'Sức khỏe shop', OAuth: 'Kết nối OAuth',
    'Real-time sync': 'Đồng bộ thời gian thực', 'Shop Setup Checklist': 'Danh sách thiết lập shop',
    'OAuth Connection': 'Kết nối OAuth', Connected: 'Đã kết nối', Synced: 'Đã đồng bộ',
    'Refresh Connection': 'Làm mới kết nối', 'Listing Quality Checker': 'Kiểm tra chất lượng tin đăng',
    'Listing Score': 'Điểm tin đăng', Hero: 'Chủ lực', OK: 'Ổn định',
    'Listing Assist — Gợi ý tối ưu': 'Trợ lý tin đăng — Gợi ý tối ưu',
    'Brand Kit': 'Bộ nhận diện thương hiệu', Primary: 'Màu chính', Accent: 'Màu nhấn',
    'Template Center': 'Kho mẫu giao diện', 'Store Decoration Preview': 'Xem trước trang shop',
    'TikTok Policy Hub — AI Impact Analysis': 'Trung tâm chính sách TikTok — Phân tích AI',
    'Compliance Checker': 'Kiểm tra tuân thủ', 'Hero SKU': 'SKU chủ lực',
    'Product Portfolio Matrix': 'Ma trận danh mục sản phẩm',
    'Star — Scale': 'Ngôi sao — Mở rộng', 'Cash Cow': 'Bò sữa', Potential: 'Tiềm năng',
    Review: 'Cần xem xét', 'Channel Integration': 'Tích hợp kênh', 'SKU Mapping': 'Ánh xạ SKU',
    'Real-time pipeline': 'Luồng dữ liệu thời gian thực', Records: 'Bản ghi', Latency: 'Độ trễ',
    'Force Sync All': 'Đồng bộ toàn bộ', 'Product Management': 'Quản lý sản phẩm',
    Margin: 'Biên lợi nhuận', Orders: 'Đơn hàng', 'SLA monitoring': 'Giám sát thời hạn xử lý',
    'Inventory Status': 'Tình trạng tồn kho', 'Returns & Cancellations': 'Hoàn hàng & hủy đơn',
    'Affiliate GMV': 'Doanh thu gộp tiếp thị liên kết', 'Active KOC': 'KOC đang hoạt động',
    'ROI TB': 'Tỷ suất hoàn vốn TB', 'Commission/tháng': 'Hoa hồng/tháng',
    'Affiliate Campaigns (SAM)': 'Chiến dịch tiếp thị liên kết (SAM)',
    'Revenue by Affiliate Source': 'Doanh thu theo nguồn tiếp thị liên kết',
    'KOC Pipeline': 'Quy trình KOC', Creator: 'Nhà sáng tạo', Tier: 'Hạng',
    Followers: 'Người theo dõi', Lifecycle: 'Vòng đời', Score: 'Điểm', Scorecard: 'Bảng điểm',
    'Agency Performance': 'Hiệu suất agency', 'Sample Pipeline': 'Quy trình gửi mẫu',
    'Content Pipeline': 'Quy trình nội dung', Views: 'Lượt xem', CTR: 'Tỷ lệ nhấp',
    'Active Campaigns': 'Chiến dịch đang chạy', Budget: 'Ngân sách', Spent: 'Đã chi',
    'Voucher Management': 'Quản lý voucher', Guardrail: 'Ngưỡng kiểm soát',
    'Ads Campaigns': 'Chiến dịch quảng cáo', ROAS: 'Tỷ suất quảng cáo', Impressions: 'Lượt hiển thị',
    'Spark Ads Wizard — Gợi ý': 'Trợ lý quảng cáo Spark — Gợi ý',
    'Revenue Trend': 'Xu hướng doanh thu', 'Cost Structure': 'Cấu trúc chi phí',
    'Return Rate': 'Tỷ lệ hoàn hàng', AOV: 'Giá trị đơn TB',
    'Attribution Analysis': 'Phân tích nguồn doanh thu',
    'Revenue by Product × Source': 'Doanh thu theo sản phẩm × nguồn',
    'P&L Breakdown': 'Phân tích lãi lỗ', 'Profit by Product': 'Lợi nhuận theo sản phẩm',
    COGS: 'Giá vốn', 'Cost Structure Detail': 'Chi tiết cấu trúc chi phí',
    Trend: 'Xu hướng', 'SKU Ranking': 'Xếp hạng SKU', Velocity: 'Tốc độ bán', Action: 'Hành động',
    'Affiliate Contribution': 'Đóng góp tiếp thị liên kết',
    'Campaign ROI Comparison': 'So sánh tỷ suất hoàn vốn chiến dịch',
    'Net Profit': 'Lợi nhuận ròng', 'Creator Ranking': 'Xếp hạng nhà sáng tạo',
    'Tier Rec.': 'Gợi ý hạng', 'Video Performance': 'Hiệu suất video',
    'Content Pattern Analysis': 'Phân tích mẫu nội dung',
    'Live Session Performance': 'Hiệu suất phiên live', Session: 'Phiên', Duration: 'Thời lượng',
    Conversion: 'Tỷ lệ chuyển đổi', 'Customer Segments': 'Phân khúc khách hàng',
    'Repeat Rate': 'Tỷ lệ mua lại', 'Cohort Analysis': 'Phân tích cohort',
    'Team Members': 'Thành viên nhóm', 'Workflow Center': 'Trung tâm quy trình',
    'Active Alerts': 'Cảnh báo đang hoạt động', Critical: 'Khẩn cấp', Warning: 'Cảnh báo',
    Info: 'Thông tin', Potential: 'Tiềm năng', 'Action Queue': 'Hàng đợi hành động',
    Assignee: 'Người phụ trách', Priority: 'Ưu tiên', Approve: 'Duyệt',
    'Automation Rules': 'Quy tắc tự động hóa', Trigger: 'Kích hoạt',
    'Product Portfolio Optimizer': 'Tối ưu danh mục sản phẩm',
    'KOC Discovery & Recommendation': 'Khám phá & gợi ý KOC',
    'Content Replication Engine': 'Công cụ nhân rộng nội dung',
    'Campaign & Budget Optimizer': 'Tối ưu chiến dịch & ngân sách',
    'Discount Strategy Automation': 'Tự động hóa chiến lược giảm giá',
    'Customer Retention Engine': 'Công cụ giữ chân khách hàng',
    'Rules active': 'Quy tắc đang bật', 'Tổng flows': 'Tổng quy trình',
    'In-App Alerts': 'Cảnh báo trong ứng dụng',
    'Notification Channels': 'Kênh thông báo', 'Audit Log': 'Nhật ký kiểm toán',
    Workflow: 'Quy trình', flow: 'quy trình', Module: 'Mô-đun', module: 'mô-đun',
    'GMV 30 ngày': 'Doanh thu gộp 30 ngày', 'AI Insights — bấm để hành động': 'Gợi ý AI — bấm để hành động',
    'Checklist setup — bấm để làm ngay': 'Danh sách thiết lập — bấm để làm ngay',
    'Chiến dịch đầu tiên — Workflow khởi chạy': 'Chiến dịch đầu tiên — Quy trình khởi chạy',
    'Tài liệu onboarding': 'Tài liệu hướng dẫn seller mới',
    'Workflow giải quyết': 'Quy trình giải quyết',
    'Xem chi tiết workflow →': 'Xem chi tiết quy trình →',
    'Chạy workflow': 'Chạy quy trình', 'Stockout risk': 'Nguy cơ hết hàng', Stable: 'Ổn định',
    'Inventory Forecast': 'Dự báo tồn kho', 'Industry Benchmark Comparison': 'So sánh chuẩn ngành',
    'Data Synchronization Status': 'Trạng thái đồng bộ dữ liệu',
    'Tổng records': 'Tổng bản ghi', 'Latency TB': 'Độ trễ TB',
    'Xem AI recommendation →': 'Xem gợi ý AI →', Confidence: 'Độ tin cậy',
    'Impact dự kiến': 'Tác động dự kiến', 'Chạy flow tự động': 'Chạy quy trình tự động',
    'Chạy flow nhập hàng': 'Chạy quy trình nhập hàng',
    'Tiềm năng Scale': 'Tiềm năng mở rộng', GMV: 'Doanh thu gộp', ROI: 'Tỷ suất hoàn vốn',
    'Tổng GMV': 'Tổng doanh thu gộp', Live: 'Livestream', Organic: 'Tự nhiên',
    'GMV Forecast — 7 ngày tới': 'Dự báo doanh thu gộp — 7 ngày tới',
    'Cảnh báo': 'Cảnh báo', 'Cần xử lý': 'Cần xử lý', 'Tuân thủ': 'Tuân thủ', 'Theo dõi': 'Theo dõi',
    'Mới': 'Mới', 'Đã đọc': 'Đã đọc', 'Giải quyết': 'Giải quyết', 'Chi tiết': 'Chi tiết',
    'Thực thi': 'Thực thi', 'Duyệt': 'Duyệt', 'Chạy': 'Chạy', 'Pause': 'Tạm dừng',
    'Scale': 'Mở rộng', 'Optimize': 'Tối ưu', 'Fix': 'Sửa lỗi',
    'Flow hoàn tất': 'Quy trình hoàn tất', 'Đang chạy flow tự động': 'Đang chạy quy trình tự động',
    'Flow tự động liên quan': 'Quy trình tự động liên quan',
    'Workflow tối ưu Ads': 'Quy trình tối ưu quảng cáo',
    'Workflow giải quyết': 'Quy trình giải quyết',
    'Chạy flow Compliance': 'Chạy quy trình tuân thủ',
    'Workflow nhân rộng content': 'Quy trình nhân rộng nội dung',
    'Workflow gửi mẫu': 'Quy trình gửi mẫu',
    'Giải quyết guardrail': 'Giải quyết ngưỡng kiểm soát',
    'Pause campaign': 'Tạm dừng chiến dịch', 'Listing Checker': 'Kiểm tra tin đăng',
    'Analytics →': 'Phân tích →', 'Quản lý voucher': 'Quản lý voucher',
    'Tổng quan + Quy trình': 'Tổng quan + Quy trình',
    'Shop Health:': 'Sức khỏe shop:',
    'Demo v2.0 · Mock Data': 'Bản demo v2.0 · Dữ liệu mẫu',
    'TikTok Shop Operations': 'Vận hành TikTok Shop',
    Orders: 'Đơn hàng', Commission: 'Hoa hồng', Units: 'Số lượng',
    'GMV 30d': 'Doanh thu gộp 30 ngày', Host: 'Người host', Pattern: 'Mẫu nội dung',
    CVR: 'Tỷ lệ chuyển đổi', Videos: 'Video', 'LTV TB': 'Giá trị vòng đời TB',
    'Loại chi phí': 'Loại chi phí', '% GMV': '% doanh thu gộp',
    'GMV Growth': 'Tăng trưởng doanh thu gộp', 'Profit Margin': 'Biên lợi nhuận',
    'Return Rate': 'Tỷ lệ hoàn hàng', 'Affiliate Share': 'Tỷ trọng tiếp thị liên kết',
    'Live Conversion': 'Chuyển đổi livestream', 'Chỉ số': 'Chỉ số',
    'Shop của bạn': 'Shop của bạn', 'Thị trường': 'Thị trường', 'Đánh giá': 'Đánh giá',
    'Sync cuối': 'Đồng bộ cuối', 'Phân khúc': 'Phân khúc', 'Số KH': 'Số khách hàng',
    'Chiến lược': 'Chiến lược', 'Vai trò': 'Vai trò', 'Phòng ban': 'Phòng ban', 'Quyền': 'Quyền',
    'Người host': 'Người host', 'Thời lượng': 'Thời lượng', 'Phiên': 'Phiên',
    '3 cases': '3 trường hợp', '↓ vs benchmark 4.8%': '↓ so với chuẩn 4.8%',
    'Margin ': 'Biên lợi nhuận ', 'Listing score ≥ 85%': 'Điểm tin đăng ≥ 85%',
    'Hoàn thiện setup shop trước khi scale': 'Hoàn thiện thiết lập shop trước khi mở rộng',
    'Các bước tự động · bấm từng bước để xem module': 'Các bước tự động · bấm từng bước để xem mô-đun',
    'Hoàn thành bước setup': 'Hoàn thành bước thiết lập',
    'Xem compliance': 'Xem tuân thủ', 'Seller Center': 'Trung tâm seller',
    'Live Checklist': 'Danh sách kiểm tra live', 'Velocity cao': 'Tốc độ bán cao',
    'compliance risk': 'rủi ro tuân thủ', 'Xem tất cả cảnh báo →': 'Xem tất cả cảnh báo →',
    'Notification Center': 'Trung tâm thông báo', 'Audit & Governance': 'Kiểm toán & quản trị',
    'Settings & Access Control': 'Cài đặt & kiểm soát truy cập',
    'Workflow Engine · Approval Flow · Task Assignment · Automation': 'Công cụ quy trình · Duyệt · Giao việc · Tự động hóa',
    'Trung tâm flow tự động liên kết modules — chạy demo từng flow': 'Trung tâm quy trình tự động liên kết mô-đun — chạy thử từng quy trình',
    'Email Alert': 'Cảnh báo email', 'Zalo Alert': 'Cảnh báo Zalo', 'Webhook': 'Webhook',
    'In-App Alert': 'Cảnh báo trong app', 'Email + Zalo report': 'Báo cáo email + Zalo',
    'Pause campaign': 'Tạm dừng chiến dịch', 'Scale sản phẩm': 'Mở rộng sản phẩm',
    'Activity Log': 'Nhật ký hoạt động', 'Shop Settings': 'Cài đặt shop',
    Integrations: 'Tích hợp', 'RBAC Roles': 'Vai trò phân quyền', 'Data Governance': 'Quản trị dữ liệu',
    Ads: 'Quảng cáo', Orders: 'Đơn hàng', 'Decision Center': 'Trung tâm quyết định',
    Content: 'Nội dung', Automation: 'Tự động hóa', Inventory: 'Tồn kho',
    User: 'Người dùng', 'Người dùng': 'Người dùng',
    Impact: 'Tác động', Priority: 'Ưu tiên', Confidence: 'Độ tin cậy'
  },
  titles: {
    'Onboarding & Setup Shop': 'Thiết lập & khởi tạo shop',
    'Product Launch': 'Ra mắt sản phẩm',
    'Store Optimization': 'Tối ưu cửa hàng',
    'Compliance & Policy Hub': 'Tuân thủ & trung tâm chính sách',
    'Education Hub & Playbook': 'Đào tạo & sổ tay vận hành',
    'Product Strategy & Hero SKU': 'Chiến lược sản phẩm & SKU chủ lực',
    'Multi-channel & SKU Mapping': 'Đa kênh & ánh xạ SKU',
    'Data Hub & TikTok Shop Sync': 'Trung tâm dữ liệu & đồng bộ TikTok Shop',
    'Product Operations': 'Vận hành sản phẩm',
    'Order Center & SLA Monitoring': 'Trung tâm đơn hàng & giám sát thời hạn',
    'Inventory Monitor & Stock Alert': 'Giám sát tồn kho & cảnh báo hết hàng',
    'Return & Cancellation Center': 'Trung tâm hoàn & hủy đơn',
    'Affiliate Center & SAM Strategy': 'Trung tâm tiếp thị liên kết & chiến lược SAM',
    'KOC CRM & Lifecycle Tracking': 'CRM KOC & theo dõi vòng đời',
    'Agency Management & ROI': 'Quản lý agency & tỷ suất hoàn vốn',
    'Sample Tracking & Sample ROI': 'Theo dõi gửi mẫu & hiệu quả mẫu',
    'Content Calendar & Task Manager': 'Lịch nội dung & quản lý công việc',
    'Livestream Operations': 'Vận hành livestream',
    'Campaign & Promotion Center': 'Trung tâm chiến dịch & khuyến mãi',
    'Voucher Guardrail & Performance': 'Kiểm soát voucher & hiệu suất',
    'Spark Ads & Campaign Setup': 'Quảng cáo Spark & thiết lập chiến dịch',
    'Executive Dashboard': 'Bảng điều hành tổng hợp',
    'Revenue Intelligence & Attribution': 'Phân tích doanh thu & nguồn gốc',
    'P&L Dashboard & Margin Analytics': 'Bảng lãi lỗ & phân tích biên lợi nhuận',
    'Cost Intelligence': 'Phân tích chi phí',
    'Product Intelligence & SKU Ranking': 'Phân tích sản phẩm & xếp hạng SKU',
    'Affiliate Analytics & Contribution': 'Phân tích tiếp thị liên kết & đóng góp',
    'KOC Scorecard & Creator Ranking': 'Bảng điểm KOC & xếp hạng nhà sáng tạo',
    'Content Intelligence & Pattern Analysis': 'Phân tích nội dung & mẫu thành công',
    'Livestream Analytics & Session Performance': 'Phân tích livestream & hiệu suất phiên',
    'Customer Intelligence': 'Phân tích khách hàng',
    'Team Management & RBAC': 'Quản lý nhóm & phân quyền',
    'Growth Assistant — AI Insight Engine': 'Trợ lý tăng trưởng — Công cụ gợi ý AI',
    'Smart Alerts': 'Cảnh báo thông minh',
    'Opportunity Engine': 'Cơ hội tăng trưởng',
    'Sales & Inventory Forecasting': 'Dự báo doanh thu & tồn kho',
    'Market Intelligence & Benchmark': 'Thông tin thị trường & so sánh chuẩn',
    'Decision Center & Action Queue': 'Trung tâm quyết định & hàng đợi hành động',
    'Automation Engine & Rule Engine': 'Công cụ tự động hóa & quy tắc',
    'Growth Optimizers': 'Bộ tối ưu tăng trưởng',
    'Workflow Center': 'Trung tâm quy trình tự động',
    'Notification Center': 'Trung tâm thông báo',
    'Audit & Governance': 'Kiểm toán & quản trị',
    'Settings & Access Control': 'Cài đặt & kiểm soát truy cập'
  }
};

function viPage(id) { return VI.pages[id] || id; }
function viLabel(text) {
  if (text == null) return text;
  const s = String(text);
  return VI.labels[s] || VI.titles[s] || VI.status[s] || s;
}
function viStatus(key) { return VI.status[key] || key; }
function viBadge(text, type) {
  const fromText = VI.labels[text] || VI.status[text];
  if (fromText) return fromText;
  const fromType = VI.status[type];
  if (fromType && (text === type || !VI.labels[text])) return fromType;
  return viLabel(text);
}
function viSource(src) { return VI.status[src] || src; }
function viEntityType(type) {
  const map = { product: 'Sản phẩm', order: 'Đơn hàng', koc: 'KOC', campaign: 'Chiến dịch', policy: 'Chính sách', alert: 'Cảnh báo', flow: 'Quy trình', insight: 'Gợi ý AI', ad: 'Quảng cáo', voucher: 'Voucher', sample: 'Gửi mẫu', content: 'Nội dung' };
  return map[type] || type;
}
